### ISSUE TITLE
Security issue with requests

### ISSUE THREAD

**Issue by Bouni** [Bouni/ard-mediathek#19]
I've never worked with pipenv before, @steffenschroeder is it enough to just update the pipfile or do we need to update the pipfile.lock as well? 
If so could you help with a pull request with the requests dependecy set to >= 2.20.0?

**Comment by steffenschroeder** [comment]
I’ll take a look

**Comment by steffenschroeder** [comment]
Basically there should be a pipenv update which updates the Pipfile.lock.
Commiting that one is sufficient

**Comment by Bouni** [comment]
@steffenschroeder So the updated pipfile I've commited is sufficent? As soon as a user starts pipenv, the .lock file generated automatically?

**Comment by steffenschroeder** [comment]
I don’t have my laptop with me. So I can’t do it myself at the moment.
Basically, without changing the pipfile you should do pipenv update request. That updates the pipfile.lock which is the solution

**Comment by Bouni** [comment]
Thnaks @steffenschroeder for solving this with #20
