### ISSUE TITLE
not working anymore?

### ISSUE THREAD

**Issue by snizzleorg** [Bouni/ard-mediathek#4]
Is this still functional? I cannot get it to download anything from ard-mediathek...

**Comment by Bouni** [comment]
I've not used it for a long time but just gave it a quick test.
Unfortunately you're right, its not working anymore.

I need to take a look at it, most likely ARD has changed their way of delivering the content which changed the URL scheme.

Maybe I can take a look at it in the lunch break.

**Comment by snizzleorg** [comment]
Ok. meanwhile I found this: https://github.com/ticky-/tatortloader this is also working for other mediathek items

**Comment by Bouni** [comment]
Ok, finally fixed ard-mediathek \o/

Not sure if subtitle support is ok, @1im1 would you mind taking a quick look at it?
