### ISSUE TITLE
Quality switch has no effect

### ISSUE THREAD

**Issue by rriemann** [Bouni/ard-mediathek#8]
I made tests with the "Babylon Berlin" series currently published and noticed that the quality switch has no effect.

**Comment by Bouni** [comment]
I'll happily accept pull requests ;-)

**Comment by steffenschroeder** [comment]
@rriemann  if you don't mind, could you take a look at  https://github.com/Bouni/ard-mediathek/pull/12 and give feedback? 
It would be even possible to download higher quality videos (1280p instead if 960p) but that would take a little bit more effort (and probably an incompatible change of the cli)
